version: "3.8"

services:
  # Frontend Service
  frontend:
    environment:
      REACT_APP_BACKEND_URL: "${LOCAL_BACKEND_URL}"
    build: ./frontend-react-js
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
      - /frontend-react-js/node_modules
    networks:
      - ${APP_NAME}-network

  # Backend Service
  backend:
    environment:
      FRONTEND_URL: "${LOCAL_FRONTEND_URL}"
      BACKEND_URL: "${LOCAL_BACKEND_URL}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io/"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
      OTEL_SERVICE_NAME: "${APP_NAME}-backend-flask"
      AWS_XRAY_URL: "${LOCAL_AWS_XRAY_URL}"
      AWS_XRAY_DAEMON_ADDRESS: "${AWS_XRAY_DAEMON_ADDRESS}"
    build: ./backend-flask
    container_name: backend
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    networks:
      - ${APP_NAME}-network

  # AWS X-Ray Daemon Service
  xray-daemon:
    image: "amazon/aws-xray-daemon"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
    command:
      - "xray -o -b xray-daemon:2000"
    ports:
      - 2000:2000/udp

# Docker Networks
networks:
  ${APP_NAME}-network:
    driver: bridge